(ns eulerclj.p002
  (:use eulerclj.euler)
  (:use clojure.test))

; ============================ PROBLEMA 002 ============================


; Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
; By starting with 1 and 2, the first 10 terms will be:
;
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
; By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
; find the sum of the even-valued terms.



(defn less-than-four-million? [n]
  (< n 4000000))

(defn p002A []
  (reduce + (filter even? 
  (take-while less-than-four-million? (lazy-seq-fibo)))))

; con closure
(defn problem002-sol2 []
  (reduce + 
    (filter even? 
      (take-while (fn [n] (< n 4000000)) (lazy-seq-fibo )))))

; con closure e notazione breve
(defn problem002-sol3 []
  (reduce + (filter even? (take-while #(< % 4000000) (lazy-seq-fibo )))))


(deftest test-p002A
  (is (= 4613732 (p002A))))

(deftest test-p002-2
  (is (= 4613732 (problem002-sol2))))

(deftest test-p002-3
  (is (= 4613732 (problem002-sol3))))
  
(defn -main
    "Risolve p002"
    [& args]
    (println "p002 ="  (p002A))
  )
